### PR TITLE
Fix Bug for duplicate open/close command

### LINKED ISSUE #122: Repeated open command gives redundant feedback
### Summary
Running `open 1` twice gives the same success message twice.

### Steps to Reproduce
1. Launch the app
2. Run `open 1`
3. Run `open 1` again

### Expected
Second attempt should indicate that the contact is already open, or ignore the command.

### Actual
Message: "Opened details for Person: Alex Yeoh" appears both times.

### Environment
- OS: Windows 11  
- Java version: 17  
- App version: v1.4.1  

### Severity
`severity.VeryLow`

### Type
`type.FeatureFlaw`

### Labels
alpha-bug

### PR DESCRIPTION
**Pull request by pranav3142**
Handles duplicate open and close commands
shows error message when user tries to close an already closed person card
Closes #122

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/CloseCommand.java [hunk 1]
```diff
@@ -40,6 +41,10 @@ public CommandResult execute(Model model) throws CommandException {
         }
 
         Person personToClose = lastShownList.get(targetIndex.getZeroBased());
+        if (!personToClose.isExpanded()) {
```
Comment (Miche1111e) [inline src/main/java/seedu/address/logic/commands/CloseCommand.java]: Good addition to distinct open contact cards and already closed contact cards

**Review by Miche1111e — APPROVED** [review]
